### ISSUE TITLE
A question about benchmark datasets

### ISSUE THREAD

**Issue by YT-bomb** [Graylab/IgFold#11]
Recently, I have tried to reproduce the evaluation of Igfold, but have not found the download location of benchmark datasets. I tried to use the method mentioned in the paper, but the number of datasets is much larger than that in the paper. So I want to know whether you can provide relevant data ?Thanks a lot.

**Comment by jeffreyruffolo** [comment]
You can find the benchmark results [here](https://data.graylab.jhu.edu/IgFold_benchmark.zip). Please note that there have been a few updates to the repository since they initial benchmarking, so results may vary slightly. I am working on an updated benchmark with the new structures that have been released since we compiled this set.

**Comment by jiaxiang-wu** [comment]
Hi @jeffreyruffolo 

Thanks for providing these benchmark results. I noticed that only IgFold-predicted PDB files, together with evaluation results are included. Could you please also add native PDB files used in your experiments, so that we can run evaluation with PDB files predicted by other pipelines?

Best,
