### ISSUE TITLE
Generated structural issues

### ISSUE THREAD

**Issue by Maikuraky** [Graylab/IgFold#2]
Why my generated structure is a coil？
the fasta is below：
>7T0K_1|Chains A, C, E, G[auth L]|S25-2 Fab light chain|Mus musculus (10090)
DIVMSQSPSSLAVSAGEKVTMSCKSSQSLLNSRTRKNYLAWYQQKPGQSPKLLIYWASTRESGVPDRFTGSGSGTDFTLTITSVQAEDLAVYYCKQSYNLRTFGGGTKLEIKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC
>7T0K_2|Chains B, D, F, H|S25-2 Fab heavy chain|Mus musculus (10090)
EVKLVESGGGLVQSGGSLRLSCATSGFTFTDYYMSWVRQPPGKALEWLGFIRNKANGYTTEYSPSVKGRFTISRDNSQSILYLQMNTLRAEDSATYYCARDHDGYYERFSYWGQGTLVTVSAAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPRA

**Comment by jeffreyruffolo** [comment]
It looks like you may be including parts of the constant domain in your sequences. Since IgFold is trained only for variable fragments, you’ll have to truncate a bit to get a good prediction. For example, if I truncate your sequences like this:

```
>H
EVKLVESGGGLVQSGGSLRLSCATSGFTFTDYYMSWVRQPPGKALEWLGFIRNKANGYTTEYSPSVKGRFTISRDNSQSILYLQMNTLRAEDSATYYCARDHDGYYERFSYWGQGTLVTVS
>L
DIVMSQSPSSLAVSAGEKVTMSCKSSQSLLNSRTRKNYLAWYQQKPGQSPKLLIYWASTRESGVPDRFTGSGSGTDFTLTITSVQAEDLAVYYCKQSYNLRTFGGGTKLEIK
```

Then you should get a well-folded structure
![image](https://user-images.githubusercontent.com/9121048/165219832-b47005e5-7b60-4346-96cd-28567ff508ea.png)

**Comment by Maikuraky** [comment]
Thanks for the suggestion, I will try it again

**Comment by jeffreyruffolo** [comment]
Closing issue for now, please reopen if the problem remains.
