### ISSUE TITLE
Prediction Problem

### ISSUE THREAD

**Issue by Tofindcode** [Graylab/IgFold#8]
Hello, IgFold is a nice job. I am a rookie in antibody prediction from sequence to 3D structure. 
The example runs smoothly, but when I run my file, the output structures are bizarre. To be exact, the amino acid chain is broken as shown in the picture. This problem doesn't happen when I truncate the sequence. I tried different files, and this happens over and over again.I would appreciate it if you could give me some advice.

![Snipaste_2022-07-22_14-19-51](https://user-images.githubusercontent.com/53810763/180375936-d6d9d93f-f7c5-4e0c-a0ca-3cbc698bab53.png)
![Snipaste_2022-07-22_14-21-49](https://user-images.githubusercontent.com/53810763/180376198-82c189f9-9e8c-405d-ab26-1f53635f3198.png)

**Comment by jeffreyruffolo** [comment]
Hello, would you be able to share the sequence that is giving this result and I can see if I am able to reproduce the output?

**Comment by Tofindcode** [comment]
> Hello, would you be able to share the sequence that is giving this result and I can see if I am able to reproduce the output?

Thanks for your reply. I want to verify the prediction results by comparing them with the actual structures.
Actually, the first picture is the structure of the heavy chain of Pembrolizumab. I tried to use the sequence of heavy and light chains to predict structure, the chains are broken. So I just tried the heavy chain. The  sequence used for prediction is as follows:
>H
QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPPCPAPEFLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQEEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKSRWQEGNVFSCSVMHEALHNHYTQKSLSLSLGK.


I also tried Atezolizumab and encountered the same problem. The sequence as follows:
>H
EVQLVESGGGLVQPGGSLRLSCAASGFTFSDSWIHWVRQAPGKGLEWVAWISPYGGSTYYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARRHWPGGFDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYASTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK
>L
DIQMTQSPSSLSASVGDRVTITCRASQDVSTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQYLYHPATFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC

**Comment by jeffreyruffolo** [comment]
It looks like the issue is how much of the sequences you're providing as input to IgFold. The model is only trained for variable fragments, so you'll have to truncate the sequences to just those domains for both heavy and light. 

When I run the first sequence (just the heavy chain) I get this output from the IgFold notebook:
<img src="https://user-images.githubusercontent.com/9121048/180627253-177800f6-857a-4759-9d8c-366a07a9cff9.png" height="200">
for sequence: QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVS

I also tried the paired sequences you provided and get this output:
<img src="https://user-images.githubusercontent.com/9121048/180627500-9e99b78d-a87a-4e87-85ed-4bd4b06801c8.png" height="200">
for sequences:
EVQLVESGGGLVQPGGSLRLSCAASGFTFSDSWIHWVRQAPGKGLEWVAWISPYGGSTYYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARRHWPGGFDYWGQGTLVTVS
DIQMTQSPSSLSASVGDRVTITCRASQDVSTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQYLYHPATFGQGTKVEIKR

If you need a full prediction for the extended sequences, a reasonable strategy might be to predict the variable part with IgFold then using homology modeling with the predicted Fv to incorporate it into a larger prediction.

**Comment by Tofindcode** [comment]
How should I get the Fv sequence from the full-length sequence? Any recommendations?

**Comment by jeffreyruffolo** [comment]
One quick way to get numbering is to run it through the [AbNum server](http://www.bioinf.org.uk/abs/abnum/). This will give you a per residue number, excluding the extra residues. Then you can see how much to use for input to IgFold.

**Comment by Tofindcode** [comment]
> One quick way to get numbering is to run it through the [AbNum server](http://www.bioinf.org.uk/abs/abnum/). This will give you a per residue number, excluding the extra residues. Then you can see how much to use for input to IgFold.

Thank you so much for your reply!
