### ISSUE TITLE
A question for the training sequence length of AntiBERTy

### ISSUE THREAD

**Issue by YiningWang2** [Graylab/IgFold#9]
Hello, I am interested in your pretrained model, AntiBERTy. I saw this model was trained on OAS. I am wondering how you deal with the training sequence length. Was this model trained on the fixed sequence length, such as 512 or 256? If trained like this, when doing inference, can this model give accurate embedding for the sequence which is longer than 512?

**Comment by jeffreyruffolo** [comment]
Hello, the AntiBERTy model uses a max sequence length of 512 for training. I think two factors would create issues for running on longer sequences. First, the model is trained only on individual variable fragments (heavy or light chain), and so it is never exposed to sequences longer than ~150 residues. Second, because we used an absolute positional embedding (the same as in the original BERT paper), you're likely to get poor performance with longer sequences.

**Comment by nnnwyn** [comment]
Okay, got it, thank you. I have another question on inference. Can AntiBERTy make inferencing on batch? If so, how can i do this? I tried to use `tokenizer.batch_encode_plus()` to generate batch tokens, but when generating the output, I met the following error:
![截屏2022-07-26 上午10 58 16](https://user-images.githubusercontent.com/25558295/180913875-217a5043-da73-4d8f-91b8-e58401152396.png)

**Comment by nnnwyn** [comment]
The above problem has been solved. But when i want to finetune AntiBERTy, I met another trouble. I am troubled in how to generate batch data. I am not sure whether it is ok  to follow your code in `IgFold.py` by using a loop.

**Comment by jeffreyruffolo** [comment]
I can try to make some example code for this in the next couple days!

**Comment by nnnwyn** [comment]
Wow！Expected to see that! Thanks you very much.
